import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import SyncUserStore from "@/components/user-store";
import { auth } from "@/auth";
import { connectToDatabase } from "@/lib/mongodb";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  await connectToDatabase();

  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistMono.variable} antialiased`}
      >
        <SyncUserStore session={session} />
        {children}
      </body>
    </html>
  );
}
